// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Be5uPn89jO2mcG-pGTrTJrmBuvkQw3E',
    appId: '1:640619258411:web:305fc03fd0c2f7a0bb006e',
    messagingSenderId: '640619258411',
    projectId: 'clothesapp-285b2',
    authDomain: 'clothesapp-285b2.firebaseapp.com',
    storageBucket: 'clothesapp-285b2.appspot.com',
    measurementId: 'G-83Z9XZ4QE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpexWotpDQ1t2uJKssdCEvc4TPHJDE9j4',
    appId: '1:640619258411:android:c1342fc4e9ded258bb006e',
    messagingSenderId: '640619258411',
    projectId: 'clothesapp-285b2',
    storageBucket: 'clothesapp-285b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNTU8F3CCXHFzhQTiCdky2O8Nyr0mFT4',
    appId: '1:640619258411:ios:c8416c38d64dcbc3bb006e',
    messagingSenderId: '640619258411',
    projectId: 'clothesapp-285b2',
    storageBucket: 'clothesapp-285b2.appspot.com',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNTU8F3CCXHFzhQTiCdky2O8Nyr0mFT4',
    appId: '1:640619258411:ios:dae0be719361c1e9bb006e',
    messagingSenderId: '640619258411',
    projectId: 'clothesapp-285b2',
    storageBucket: 'clothesapp-285b2.appspot.com',
    iosBundleId: 'com.example.clothesApp.RunnerTests',
  );
}
